// Clipman interoperability fixture generator.
//
// This compiles against the real Windows client sources, so the blobs it
// writes are produced by the canonical ClipDatabaseFile and
// ServerDatabaseIdentity implementations rather than by a reimplementation.
// A fixture that disagrees with this output is a real cross-client break.
//
// C# 5 only: this is built by the .NET Framework 4.0 compiler alongside src\,
// so no string interpolation, no null-conditional operators, and no nameof.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace Clipman.Fixtures
{
    internal static class Program
    {
        private static int Main(string[] args)
        {
            try
            {
                if (args.Length >= 1 && args[0] == "verify")
                {
                    if (args.Length < 2)
                    {
                        Console.Error.WriteLine("usage: ClipmanFixtures verify <directory>");
                        return 2;
                    }
                    return Verify(args[1]);
                }
                if (args.Length < 1)
                {
                    Console.Error.WriteLine("usage: ClipmanFixtures <output-directory> | ClipmanFixtures verify <directory>");
                    return 2;
                }
                Generate(args[0]);
                return 0;
            }
            catch (Exception error)
            {
                Console.Error.WriteLine("fixture generation failed: " + error.Message);
                return 1;
            }
        }

        // A fixed instant keeps regenerated fixtures byte-stable except for the
        // random salt and IV, so a rebuild produces a reviewable diff instead of
        // rewriting every timestamp.
        private const long BaseUnixMs = 1780000000000L;

        private static void Generate(string directory)
        {
            Directory.CreateDirectory(directory);
            var manifest = new StringBuilder();
            manifest.Append("{\n");
            manifest.Append("  \"version\": 1,\n");
            manifest.Append("  \"generator\": \"windows-csharp\",\n");
            manifest.Append("  \"note\": \"Generated by tools/ClipmanFixtures against src/ClipDatabaseFile.cs and src/ServerDatabaseIdentity.cs. Do not hand-edit.\",\n");
            manifest.Append("  \"identity\": [\n");

            var identity = new List<string>();
            AddIdentity(identity, "ascii", "token-abc-123", "correct horse battery staple");
            AddIdentity(identity, "unicode-password", "token-abc-123", "p\u00e4ssw\u00f6rd-\u65e5\u672c\u8a9e-\U0001F510");
            AddIdentity(identity, "unicode-token", "\u30c8\u30fc\u30af\u30f3-123", "plain-password");
            AddIdentity(identity, "token-needs-trimming", "  token-abc-123\t\n", "correct horse battery staple");
            AddIdentity(identity, "single-character", "t", "p");
            AddIdentity(identity, "long-password", "token-abc-123", new string('p', 512));
            AddIdentity(identity, "password-with-newline", "token-abc-123", "line one\nline two");
            AddIdentity(identity, "empty-password-has-no-bucket", "token-abc-123", "");
            AddIdentity(identity, "empty-token-has-no-bucket", "", "correct horse battery staple");
            manifest.Append(string.Join(",\n", identity.ToArray()));
            manifest.Append("\n  ],\n");
            manifest.Append("  \"databases\": [\n");

            var databases = new List<string>();
            databases.Add(WriteDatabase(directory, "plain-basic", "", BasicDatabase()));
            databases.Add(WriteDatabase(directory, "plain-empty", "", EmptyDatabase()));
            databases.Add(WriteDatabase(directory, "encrypted-basic", "correct horse battery staple", BasicDatabase()));
            databases.Add(WriteDatabase(directory, "encrypted-unicode-password", "p\u00e4ssw\u00f6rd-\u65e5\u672c\u8a9e-\U0001F510", BasicDatabase()));
            databases.Add(WriteDatabase(directory, "plain-awkward-text", "", AwkwardTextDatabase()));
            databases.Add(WriteDatabase(directory, "encrypted-awkward-text", "correct horse battery staple", AwkwardTextDatabase()));
            databases.Add(WriteDatabase(directory, "plain-rich-text", "", RichTextDatabase()));
            databases.Add(WriteDatabase(directory, "plain-tombstones", "", TombstoneDatabase()));
            manifest.Append(string.Join(",\n", databases.ToArray()));
            manifest.Append("\n  ]\n}\n");

            File.WriteAllText(Path.Combine(directory, "manifest.json"), manifest.ToString(), new UTF8Encoding(false));
            Console.Out.WriteLine("wrote " + databases.Count + " databases and " + identity.Count + " identity vectors to " + directory);
        }

        private static void AddIdentity(List<string> into, string name, string token, string password)
        {
            var id = ServerDatabaseIdentity.FromTokenAndPassword(token, password);
            var item = new StringBuilder();
            item.Append("    { \"name\": ").Append(Quote(name));
            item.Append(", \"token\": ").Append(Quote(token));
            item.Append(", \"password\": ").Append(Quote(password));
            item.Append(", \"databaseId\": ").Append(Quote(id)).Append(" }");
            into.Add(item.ToString());
        }

        private static string WriteDatabase(string directory, string name, string password, ClipDatabase database)
        {
            var blobPath = Path.Combine(directory, name + ".clipdb");
            if (File.Exists(blobPath))
            {
                // SaveAtomic reuses an existing file's salt, which would defeat
                // the point of regenerating the fixture.
                File.Delete(blobPath);
            }
            ClipDatabaseFile.SaveAtomic(blobPath, database, password);

            // Read it straight back through the canonical loader so the
            // expectation file records what Windows itself sees, not what this
            // generator believes it wrote.
            var loaded = ClipDatabaseFile.Load(blobPath, password);
            File.WriteAllText(Path.Combine(directory, name + ".expected.json"), DescribeDatabase(loaded), new UTF8Encoding(false));

            var container = string.IsNullOrEmpty(password) ? "CLIPDB1" : "CLIPDB2";
            var item = new StringBuilder();
            item.Append("    { \"name\": ").Append(Quote(name));
            item.Append(", \"file\": ").Append(Quote(name + ".clipdb"));
            item.Append(", \"expected\": ").Append(Quote(name + ".expected.json"));
            item.Append(", \"password\": ").Append(Quote(password));
            item.Append(", \"container\": ").Append(Quote(container)).Append(" }");
            return item.ToString();
        }

        // DescribeDatabase writes a deliberately reduced, lowercase-keyed view of
        // the database. It is an assertion target, not the wire format: keeping
        // it distinct stops a reader from mistaking it for the JSON inside the
        // blob, and keeps it stable if a client adds a field.
        private static string DescribeDatabase(ClipDatabase database)
        {
            var entries = new List<ClipEntry>(database.Entries);
            entries.Sort(delegate(ClipEntry left, ClipEntry right) { return string.CompareOrdinal(left.Id, right.Id); });
            var deleted = new List<DeletedClipEntry>(database.DeletedEntries);
            deleted.Sort(delegate(DeletedClipEntry left, DeletedClipEntry right) { return string.CompareOrdinal(left.Id, right.Id); });

            var text = new StringBuilder();
            text.Append("{\n");
            text.Append("  \"version\": ").Append(Number(database.Version)).Append(",\n");
            text.Append("  \"updatedUnixMs\": ").Append(Number(database.UpdatedUnixMs)).Append(",\n");
            text.Append("  \"entries\": [\n");
            for (var index = 0; index < entries.Count; index++)
            {
                var entry = entries[index];
                text.Append("    {");
                text.Append(" \"id\": ").Append(Quote(entry.Id));
                text.Append(", \"text\": ").Append(Quote(entry.Text));
                text.Append(", \"name\": ").Append(Quote(entry.Name));
                text.Append(", \"group\": ").Append(Quote(entry.Group));
                text.Append(", \"sourceMachine\": ").Append(Quote(entry.SourceMachine));
                text.Append(", \"createdUnixMs\": ").Append(Number(entry.CreatedUnixMs));
                text.Append(", \"lastUsedUnixMs\": ").Append(Number(entry.LastUsedUnixMs));
                text.Append(", \"pinned\": ").Append(entry.Pinned ? "true" : "false");
                text.Append(", \"isTemplate\": ").Append(entry.IsTemplate ? "true" : "false");
                text.Append(", \"manualOrder\": ").Append(Number(entry.ManualOrder));
                text.Append(", \"hasRichText\": ").Append(entry.RichText != null ? "true" : "false");
                text.Append(" }");
                if (index + 1 < entries.Count) text.Append(",");
                text.Append("\n");
            }
            text.Append("  ],\n");
            text.Append("  \"deleted\": [\n");
            for (var index = 0; index < deleted.Count; index++)
            {
                var marker = deleted[index];
                text.Append("    {");
                text.Append(" \"id\": ").Append(Quote(marker.Id));
                text.Append(", \"textHash\": ").Append(Quote(marker.TextHash));
                text.Append(", \"deletedUnixMs\": ").Append(Number(marker.DeletedUnixMs));
                text.Append(", \"sourceMachine\": ").Append(Quote(marker.SourceMachine));
                text.Append(" }");
                if (index + 1 < deleted.Count) text.Append(",");
                text.Append("\n");
            }
            text.Append("  ]\n}\n");
            return text.ToString();
        }

        private static ClipDatabase EmptyDatabase()
        {
            var database = new ClipDatabase();
            database.Version = 1;
            database.UpdatedUnixMs = BaseUnixMs;
            database.Entries = new List<ClipEntry>();
            database.DeletedEntries = new List<DeletedClipEntry>();
            return database;
        }

        private static ClipEntry NewEntry(string id, string text)
        {
            var entry = new ClipEntry();
            entry.Id = id;
            entry.Text = text;
            entry.Name = string.Empty;
            entry.Group = string.Empty;
            entry.SourceMachine = "windows-fixture";
            entry.CreatedUnixMs = BaseUnixMs;
            entry.LastUsedUnixMs = BaseUnixMs;
            entry.ModifiedUnixMs = BaseUnixMs;
            entry.ManualOrder = 1;
            return entry;
        }

        private static ClipDatabase BasicDatabase()
        {
            var database = EmptyDatabase();

            var plain = NewEntry("0123456789abcdef0123456789abcdef", "kubectl get pods -A");
            plain.ManualOrder = 1;

            var named = NewEntry("11111111222222223333333344444444", "export DATABASE_URL=postgres://localhost/app");
            named.Name = "database url";
            named.Group = "ops";
            named.LastUsedUnixMs = BaseUnixMs + 60000;
            named.ManualOrder = 2;

            var pinned = NewEntry("aaaaaaaabbbbbbbbccccccccdddddddd", "ssh web-01");
            pinned.Pinned = true;
            pinned.ManualOrder = 3;

            var template = NewEntry("99999999888888887777777766666666", "{{year_full}}-{{month_num_padded}}-{{day_of_month_padded}}");
            template.Name = "today";
            template.IsTemplate = true;
            template.ManualOrder = 4;

            database.Entries.Add(plain);
            database.Entries.Add(named);
            database.Entries.Add(pinned);
            database.Entries.Add(template);
            return database;
        }

        // AwkwardTextDatabase covers the text shapes most likely to be mangled
        // by an encoding, escaping, or line-ending bug in another client.
        private static ClipDatabase AwkwardTextDatabase()
        {
            var database = EmptyDatabase();

            database.Entries.Add(NewEntry("10000000000000000000000000000001", "crlf\r\nline\r\nendings"));
            database.Entries.Add(NewEntry("10000000000000000000000000000002", "lf\nline\nendings"));
            database.Entries.Add(NewEntry("10000000000000000000000000000003", "trailing whitespace   \t  "));
            database.Entries.Add(NewEntry("10000000000000000000000000000004", "no trailing newline"));
            database.Entries.Add(NewEntry("10000000000000000000000000000005", "with trailing newline\n"));
            database.Entries.Add(NewEntry("10000000000000000000000000000006", "nul\0byte"));
            database.Entries.Add(NewEntry("10000000000000000000000000000007", "\u65e5\u672c\u8a9e \u0645\u0631\u062d\u0628\u0627 \u0448\u0438\u0431\u0431\u043e\u043b\u0435\u0442"));
            database.Entries.Add(NewEntry("10000000000000000000000000000008", "emoji \U0001F510\U0001F44D\U0001F3F3\ufe0f\u200d\U0001F308"));
            database.Entries.Add(NewEntry("10000000000000000000000000000009", "quotes \" ' ` and backslash \\ and tab \t"));
            database.Entries.Add(NewEntry("1000000000000000000000000000000a", "html <script>alert('x')</script> & ampersand"));
            database.Entries.Add(NewEntry("1000000000000000000000000000000b", "json {\"key\": [1, 2, null]}"));
            return database;
        }

        // RichTextDatabase exists so other clients can prove they preserve
        // fields they do not themselves understand. The CLI and Linux backend
        // have no RichText field and must round-trip it untouched.
        private static ClipDatabase RichTextDatabase()
        {
            var database = EmptyDatabase();

            var rich = NewEntry("20000000000000000000000000000001", "styled text");
            rich.Name = "rich";
            rich.RichText = new RichTextPayload();
            rich.RichText.Version = 1;
            rich.RichText.HtmlFragment = "<p><b>styled</b> text</p>";
            rich.RichText.RtfBase64 = Convert.ToBase64String(Encoding.ASCII.GetBytes(@"{\rtf1 styled text}"));
            rich.RichText.PreferredFormat = "html";
            rich.RichTextUpdatedUnixMs = BaseUnixMs;

            var plain = NewEntry("20000000000000000000000000000002", "ordinary text");
            plain.ManualOrder = 2;

            database.Entries.Add(rich);
            database.Entries.Add(plain);
            return database;
        }

        private static ClipDatabase TombstoneDatabase()
        {
            var database = EmptyDatabase();
            database.Entries.Add(NewEntry("30000000000000000000000000000001", "surviving entry"));

            var recent = new DeletedClipEntry();
            recent.Id = "30000000000000000000000000000002";
            recent.TextHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
            recent.DeletedUnixMs = BaseUnixMs;
            recent.SourceMachine = "windows-fixture";

            // Just inside the documented 90-day retention window.
            var nearBoundary = new DeletedClipEntry();
            nearBoundary.Id = "30000000000000000000000000000003";
            nearBoundary.TextHash = "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03";
            nearBoundary.DeletedUnixMs = BaseUnixMs - (89L * 24L * 60L * 60L * 1000L);
            nearBoundary.SourceMachine = "windows-fixture";

            // Deliberately blank source machine and text hash.
            var sparse = new DeletedClipEntry();
            sparse.Id = "30000000000000000000000000000004";
            sparse.TextHash = string.Empty;
            sparse.DeletedUnixMs = BaseUnixMs;
            sparse.SourceMachine = string.Empty;

            database.DeletedEntries.Add(recent);
            database.DeletedEntries.Add(nearBoundary);
            database.DeletedEntries.Add(sparse);
            return database;
        }

        // Verify reads blobs another client wrote and reports whether the
        // canonical Windows loader accepts them. It closes the loop the other
        // way round: fixtures prove Windows-to-others, this proves others-to-Windows.
        private static int Verify(string directory)
        {
            if (!Directory.Exists(directory))
            {
                Console.Error.WriteLine("no such directory: " + directory);
                return 2;
            }
            var failures = 0;
            var checkedCount = 0;
            var files = Directory.GetFiles(directory, "*.clipdb");
            Array.Sort(files, StringComparer.OrdinalIgnoreCase);
            foreach (var file in files)
            {
                var name = Path.GetFileNameWithoutExtension(file);
                var passwordFile = Path.Combine(directory, name + ".password");
                var password = File.Exists(passwordFile) ? File.ReadAllText(passwordFile, Encoding.UTF8) : string.Empty;
                checkedCount++;
                try
                {
                    var database = ClipDatabaseFile.Load(file, password);
                    Console.Out.WriteLine("ok    " + name + ": " + database.Entries.Count + " entries, " + database.DeletedEntries.Count + " tombstones");
                    var expected = Path.Combine(directory, name + ".expected.json");
                    if (File.Exists(expected))
                    {
                        var actual = DescribeDatabase(database);
                        if (!string.Equals(actual, File.ReadAllText(expected, Encoding.UTF8), StringComparison.Ordinal))
                        {
                            Console.Error.WriteLine("FAIL  " + name + ": contents differ from " + Path.GetFileName(expected));
                            failures++;
                        }
                    }
                }
                catch (Exception error)
                {
                    Console.Error.WriteLine("FAIL  " + name + ": " + error.Message);
                    failures++;
                }
            }
            Console.Out.WriteLine(checkedCount + " checked, " + failures + " failed");
            return failures == 0 ? 0 : 1;
        }

        private static string Number(long value)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }

        // Quote emits JSON with every non-ASCII and control character escaped,
        // so the fixture files stay reviewable as plain ASCII in a diff and are
        // not silently altered by an editor's encoding.
        private static string Quote(string value)
        {
            if (value == null) return "null";
            var text = new StringBuilder("\"");
            foreach (var character in value)
            {
                switch (character)
                {
                    case '"': text.Append("\\\""); break;
                    case '\\': text.Append("\\\\"); break;
                    case '\b': text.Append("\\b"); break;
                    case '\f': text.Append("\\f"); break;
                    case '\n': text.Append("\\n"); break;
                    case '\r': text.Append("\\r"); break;
                    case '\t': text.Append("\\t"); break;
                    default:
                        if (character < 0x20 || character > 0x7e)
                        {
                            text.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            text.Append(character);
                        }
                        break;
                }
            }
            return text.Append("\"").ToString();
        }
    }
}
